/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cine;

import java.awt.Image;
import java.awt.event.ComponentAdapter;
import java.awt.event.ComponentEvent;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.net.URL;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.SwingUtilities;

/**
 *
 * @author CBN
 */
public class FrmVentanaPelicula extends javax.swing.JFrame {

    /**
     * Creates new form FrmVentanaPelicula
     */
    
    private FrmInicio inicio;
    private String titulo;
    private String genero;
    private String director;
    private String duracion;
    
    public FrmVentanaPelicula() {
        initComponents();
        
        this.setLocationRelativeTo(null);

        this.addComponentListener(new ComponentAdapter() {
            @Override
            public void componentShown(ComponentEvent e) {
                loadAndAdjustImage();
                removeComponentListener(this);
            }

            @Override
            public void componentResized(ComponentEvent e) {
                loadAndAdjustImage();
            }
        });
    }

    public void setTitulo(String titulo){
        this.titulo = titulo;
        LblTitulo.setText(titulo);
    }
    public void setGenero(String genero){
        this.genero = genero;
        LblGenero.setText(genero);
    }
    public void setDirector(String director){
        this.director = director;
        LblDirector.setText(director);
    }
    public void setDuracion(String duracion){
        this.duracion = duracion;
        LblDuracion.setText(duracion);
    }
    
    private void loadAndAdjustImage() {
        String resourcePath = "/Imagenes/titanic.jpg";
        URL url = getClass().getResource(resourcePath);

        if (url == null) {
            System.err.println("No se encontró recurso en classpath: " + resourcePath);
            File file = new File("src/Imagenes/titanic.jpg");
            if (file.exists()) {
                try {
                    BufferedImage img = ImageIO.read(file);
                    AjusteImagen(LblImagen, img);
                } catch (IOException ex) {
                    ex.printStackTrace();
                }
            } else {
                System.err.println("Tampoco existe src/Imagenes/titanic.jpg");
            }
            return;
        }

        try {
            BufferedImage img = ImageIO.read(url);
            AjusteImagen(LblImagen, img);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
    
    public void AjusteImagen(JLabel labelName, BufferedImage image) {
        int w = labelName.getWidth();
        int h = labelName.getHeight();

        // si el label aún no tiene tamaño, reintentar un poco después en el EDT
        if (w <= 0 || h <= 0) {
            SwingUtilities.invokeLater(() -> AjusteImagen(labelName, image));
            return;
        }

        Image scaled = image.getScaledInstance(w, h, Image.SCALE_SMOOTH);
        labelName.setIcon(new ImageIcon(scaled));
        labelName.revalidate();
        labelName.repaint();
    }
    
    public void setInicio( FrmInicio inicio) {
        this.inicio = inicio;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LblImagen = new javax.swing.JLabel();
        LblGenero = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        LblDirector = new javax.swing.JLabel();
        LblDuracion = new javax.swing.JLabel();
        LblSinopsis = new javax.swing.JLabel();
        BtnAtras = new javax.swing.JButton();
        BtnComprar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        LblImagen.setText("jLabel1");

        LblGenero.setText("jLabel2");

        LblTitulo.setText("jLabel3");

        LblDirector.setText("jLabel4");

        LblDuracion.setText("jLabel5");

        LblSinopsis.setText("jLabel6");

        BtnAtras.setText("X");
        BtnAtras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAtrasActionPerformed(evt);
            }
        });

        BtnComprar.setText("Comprar voleta");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(182, 182, 182)
                            .addComponent(LblImagen))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(61, 61, 61)
                            .addComponent(LblTitulo)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(LblGenero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblDirector)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(LblDuracion)
                        .addContainerGap(65, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BtnAtras, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(LblSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(142, 142, 142)
                        .addComponent(BtnComprar)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(LblImagen))
                    .addComponent(BtnAtras))
                .addGap(78, 78, 78)
                .addComponent(LblTitulo)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDirector)
                    .addComponent(LblGenero)
                    .addComponent(LblDuracion))
                .addGap(64, 64, 64)
                .addComponent(LblSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(BtnComprar)
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAtrasActionPerformed
        // TODO add your handling code here:
        inicio.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_BtnAtrasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmVentanaPelicula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmVentanaPelicula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAtras;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JLabel LblDirector;
    private javax.swing.JLabel LblDuracion;
    private javax.swing.JLabel LblGenero;
    private javax.swing.JLabel LblImagen;
    private javax.swing.JLabel LblSinopsis;
    private javax.swing.JLabel LblTitulo;
    // End of variables declaration//GEN-END:variables
}
