/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cine.FrmPrincipal;

import cine.FrmInternas.JIFrmAgregarPeliculas;
import cine.FrmInternas.JIFrmReportes;
import cine.FrmInternas.JIFrmPerfil;
import cine.FrmInternas.JIFrmTablaTicket;
import cine.FrmInternas.JIFrmFunciones;
import cine.FrmInternas.JIFrmTablapelicula;
import cine.FrmInternas.JIFrmBuscarPelicula;
import cine.Clases.Sesion;
import javax.swing.JFrame;

/**
 *
 * @author 57300
 */
public class JIFrmMenu extends javax.swing.JFrame {

    /**
     * Creates new form FrmMenu
     */
    
    public JIFrmMenu() {
        initComponents();
    }
    
    public void mostrarMenuGestion(boolean mostrar) {
        MenuGestion.setVisible(mostrar);
    }
    public void mostrarMenuREporte(boolean mostrar){
        MenuReportes.setVisible(mostrar);
    }
    
    public void ventanaMenu(){
        this.dispose();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PrinsipalDesktop = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu2 = new javax.swing.JMenu();
        MenuPerfil = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        MenuReportes = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        MenuGestion = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        MenuFuncion = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout PrinsipalDesktopLayout = new javax.swing.GroupLayout(PrinsipalDesktop);
        PrinsipalDesktop.setLayout(PrinsipalDesktopLayout);
        PrinsipalDesktopLayout.setHorizontalGroup(
            PrinsipalDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        PrinsipalDesktopLayout.setVerticalGroup(
            PrinsipalDesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        jMenu2.setBackground(new java.awt.Color(139, 220, 224));
        jMenu2.setText("Perfil");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        MenuPerfil.setBackground(new java.awt.Color(255, 204, 213));
        MenuPerfil.setText("File");

        jMenuItem1.setText("Buscar");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        MenuPerfil.add(jMenuItem1);

        jMenuItem5.setText("Ticket");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        MenuPerfil.add(jMenuItem5);

        jMenuBar1.add(MenuPerfil);

        MenuReportes.setBackground(new java.awt.Color(186, 245, 208));
        MenuReportes.setText("Reportes");

        jMenuItem4.setText("Reportes");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        MenuReportes.add(jMenuItem4);

        jMenuBar1.add(MenuReportes);

        MenuGestion.setBackground(new java.awt.Color(216, 200, 255));
        MenuGestion.setText("Gestion");

        jMenuItem2.setText("Agregar pelicula");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        MenuGestion.add(jMenuItem2);

        jMenuItem3.setText("Tabla Pelicula");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        MenuGestion.add(jMenuItem3);

        MenuFuncion.setText("Funcion");
        MenuFuncion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuFuncionActionPerformed(evt);
            }
        });
        MenuGestion.add(MenuFuncion);

        jMenuBar1.add(MenuGestion);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrinsipalDesktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PrinsipalDesktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        JIFrmAgregarPeliculas agregar = new JIFrmAgregarPeliculas();
        PrinsipalDesktop.add(agregar);
        agregar.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        JIFrmTablapelicula TablaPelicula = new JIFrmTablapelicula();
        PrinsipalDesktop.add(TablaPelicula);
        TablaPelicula.mostrarInfo();
        TablaPelicula.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void MenuFuncionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuFuncionActionPerformed
        // TODO add your handling code here:
        JIFrmFunciones funcion = new JIFrmFunciones();
        PrinsipalDesktop.add(funcion);
        funcion.setVisible(true);
        funcion.AgregarGuia();
        funcion.mostrarInfo();
    }//GEN-LAST:event_MenuFuncionActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        JIFrmBuscarPelicula Buscar = new JIFrmBuscarPelicula();
        PrinsipalDesktop.add(Buscar);
        Buscar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        JIFrmReportes reportes = new JIFrmReportes();
        PrinsipalDesktop.add(reportes);
        reportes.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        
        JIFrmPerfil perfil = new JIFrmPerfil(Sesion.usuarioActivo);
        PrinsipalDesktop.add(perfil);
        perfil.mostrarPerfilPorId();
        perfil.setVisible(true);
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        JIFrmTablaTicket ticket = new JIFrmTablaTicket();
        ticket.mostrarTodosMisTickets();
        PrinsipalDesktop.add(ticket);
        ticket.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JIFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JIFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JIFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JIFrmMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JIFrmMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuFuncion;
    private javax.swing.JMenu MenuGestion;
    private javax.swing.JMenu MenuPerfil;
    private javax.swing.JMenu MenuReportes;
    private javax.swing.JDesktopPane PrinsipalDesktop;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    // End of variables declaration//GEN-END:variables
}
