/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.Cuenta;
import cine.Clases.ConexionBD;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 57300
 */
public class JIFrmTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmTicket
     */
    
    ConexionBD conn;
    int id;
    
    String titulo,Sala,Inicio,Fin,sillas;
    double total;
    ArrayList<Integer> silla;
    ArrayList<Integer> asientoId = new  ArrayList();
    ArrayList<Integer> idreserva = new  ArrayList();
    private Cuenta cuenta;
 
    public JIFrmTicket(int id,String titulo,String Sala,String Inicio,String Fin,double total,Cuenta cuenta, ArrayList asientoId) {
        initComponents();
        this.id = id;
        this.titulo = titulo;
        this.Sala = Sala;
        this.Inicio = Inicio;
        this.Fin = Fin;
        this.total = total;
        this.cuenta = cuenta;
        this.asientoId = asientoId;
        silla = new ArrayList();
        conn = new ConexionBD();
        cambiardatos();
        addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent e) {
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Cancelar la reserva?");
                if (respuesta == JOptionPane.YES_OPTION) {
                    cancelarAsiento();
                    dispose();
                }
            }
        });
        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
    }
    
    public void cambiardatos(){
        Lblpelicula.setText(titulo);
        LblInicio.setText(Inicio);
        LblFin.setText(Fin);
        LblSala.setText(Sala);
        LblPrecio.setText(""+total);   
        StringBuilder texto = new StringBuilder("");

        for (int i = 0; i < silla.size(); i++) {
            texto.append(silla.get(i));
            if (i < silla.size() - 1) {
                texto.append(", ");
            }
        }
        LblSillas.setText(texto.toString());
        sillas = texto.toString();
    }
    
    public void insertarReserva(int idc , double total){
        int ide = cuenta.getIde();
        try {
            Connection con = conn.Conexion();
            CallableStatement cstmt = con.prepareCall("call insertar_reserva(?, ?, ?, ?)");
            
            if (idc == 0) {
                cstmt.setNull(1, Types.INTEGER);
                cstmt.setInt(2,ide); 
            } else {
                cstmt.setInt(1, idc);
                cstmt.setNull(2, Types.INTEGER); 
            }                  
                               
            cstmt.setDouble(3, total);
            cstmt.registerOutParameter(4, Types.INTEGER);            
            
            cstmt.execute();
            int reservaId = cstmt.getInt(4);  
            
            idreserva.clear();
            idreserva.add(reservaId);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar " + e.getMessage());
        }
    }
    
    private void cancelarAsiento() {
        for (int i = 0; i < asientoId.size(); i++) {
            int idAsiento = asientoId.get(i);
            try{
                Connection con = conn.Conexion();
                String sql = "call eliminar_asiento(?)";
                CallableStatement cstmt = con.prepareCall(sql);
               cstmt.setInt(1, idAsiento);
               int filas = cstmt.executeUpdate();

               if (filas > 0) {
                   JOptionPane.showMessageDialog(null, "Asiento cancelado");
               } else {
                   JOptionPane.showMessageDialog(null, "No se encontró el asiento");
               }

           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Error al cancelar asiento: " + e.getMessage());
           }
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Lblpelicula = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        LblInicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblSillas = new javax.swing.JLabel();
        BtnComprar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LblFin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LblSala = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Pelicula:");

        Lblpelicula.setText("jLabel2");

        jLabel2.setText("Iniocio:");

        LblInicio.setText("jLabel2");

        jLabel3.setText("Sillas:");

        LblSillas.setText("jLabel4");

        BtnComprar.setText("Comprar");
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });

        jLabel7.setText("Fin:");

        LblFin.setText("jLabel2");

        jLabel8.setText("Sala:");

        LblSala.setText("jLabel2");

        jLabel9.setText("Precio:");

        LblPrecio.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblInicio))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Lblpelicula)))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblSala))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LblFin))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnComprar)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LblSillas)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LblPrecio)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(Lblpelicula))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel8)
                        .addComponent(LblSala, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(LblInicio))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LblSillas)
                            .addComponent(jLabel9)
                            .addComponent(LblPrecio)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel7)
                        .addComponent(LblFin, javax.swing.GroupLayout.Alignment.TRAILING)))
                .addGap(40, 40, 40)
                .addComponent(BtnComprar)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        // TODO add your handling code here:
           insertarReserva(cuenta.getId(),  total);
           
           int reserva = idreserva.get(0);
           
           JIFrmPago pago = new JIFrmPago(reserva, id, total, cuenta,asientoId);
           getDesktopPane().add(pago);
           pago.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_BtnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnComprar;
    private javax.swing.JLabel LblFin;
    private javax.swing.JLabel LblInicio;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblSala;
    private javax.swing.JLabel LblSillas;
    private javax.swing.JLabel Lblpelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
