/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.Peliculas;
import cine.Clases.ConexionBD;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author 57300
 */
public class JIFrmAgregarPeliculas extends javax.swing.JInternalFrame {

    /**
     * Creates new form FrmAgregarPeliculas1
     */
    ConexionBD conn;
    private int id;
    private String titulo;
    private String genero;
    private String director;
    private String duracion;
    private String sinopsis;
    private String idioma;
    private String Estreno;
    
    public JIFrmAgregarPeliculas() {
        initComponents();
        conn = new ConexionBD();
        LlenarComboGenero();
    }

    
    public void AgrgarPelicula(){
        Date fecha = DataFecha.getDate();
        
        if(!TxtTitulo.getText().isEmpty() && !TxtDirector.getText().isEmpty() 
                && !TxtDuracion.getText().isEmpty() && fecha != null && !TxtIdioma.getText().isEmpty()
                && !TxtSinopsis.getText().isEmpty())
        {
            if (!TxtGenero.getText().isEmpty() && ComboGenero.getSelectedIndex()> 0) {
                   JOptionPane.showMessageDialog(this, 
                    "Solo puede llenar uno de los dos campos: escriba el género o selecciónelo, no ambos.");
            } else if (TxtGenero.getText().isEmpty() && ComboGenero.getSelectedIndex() <=0) {
                JOptionPane.showMessageDialog(this, 
                    "Debe escribir el género o seleccionarlo.");
            } else {
                if(!TxtGenero.getText().isEmpty()){
                    genero = TxtGenero.getText();
                }else{
                    genero = ComboGenero.getSelectedItem().toString();
                }
                
                int id = 0;
                sinopsis = TxtSinopsis.getText();
                idioma = TxtIdioma.getText();
                titulo = TxtTitulo.getText();
                duracion = TxtDuracion.getText();
                Estreno = new SimpleDateFormat("yyyy-MM-dd").format(fecha);
                director = TxtDirector.getText();
                Peliculas pelicula =new Peliculas(id,titulo,genero,duracion,Estreno,director,sinopsis,idioma);
                try {
                    Connection con = conn.Conexion();
                    CallableStatement cstmt = con.prepareCall("call AgregarPelicula(?, ?, ?, ?, ?, ?, ?)");
                    cstmt.setString(1, pelicula.getTitulo());
                    cstmt.setString(2, pelicula.getDirector());
                    cstmt.setString(3, pelicula.getSinopsis());
                    cstmt.setString(4, pelicula.getDuracion());
                    cstmt.setString(5, pelicula.getEstreno());
                    cstmt.setString(6, pelicula.getIdioma());
                    cstmt.setString(7, pelicula.getGenero());            

                    cstmt.execute();

                    JOptionPane.showMessageDialog(null, "Película agregada correctamente");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Error: al guardar " + e.getMessage());
                }
            }
        }else
        {
            JOptionPane.showMessageDialog(rootPane, "Faltan paremetros");
        }
    }
    
    public void LlenarComboGenero(){
        try {
            Connection con = conn.Conexion();
            String sql = "call listar_generos()";
            
            CallableStatement  cstmt  = con.prepareCall(sql);
            
            ResultSet resultado = cstmt.executeQuery();
            
            ComboGenero.removeAllItems();
            ComboGenero.addItem("Seleccione...");
            
            while(resultado.next()){
                ComboGenero.addItem(resultado.getString("nombre_genero"));
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar genero" + e);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel5 = new javax.swing.JLabel();
        TxtDuracion = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        TxtSinopsis = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        TxtTitulo = new javax.swing.JTextField();
        BtnAgregar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtDirector = new javax.swing.JTextField();
        TxtIdioma = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ComboGenero = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        TxtGenero = new javax.swing.JTextField();
        DataFecha = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel5.setText("Duracion:");

        jLabel6.setText("Sinopsis:");

        jLabel1.setText("Titulo:");

        BtnAgregar.setText("Agregar");
        BtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAgregarActionPerformed(evt);
            }
        });

        jLabel2.setText("Director:");

        jLabel7.setText("Idioma:");

        TxtDirector.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtDirectorActionPerformed(evt);
            }
        });

        jLabel3.setText("Genero:");

        ComboGenero.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("Fecha:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(21, 21, 21)
                            .addComponent(jLabel6))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 38, Short.MAX_VALUE)
                        .addComponent(TxtSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(TxtGenero, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ComboGenero, javax.swing.GroupLayout.Alignment.LEADING, 0, 130, Short.MAX_VALUE)
                            .addComponent(TxtDuracion, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(TxtTitulo, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(DataFecha, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addComponent(TxtIdioma)
                            .addComponent(TxtDirector, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(TxtTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(TxtDirector, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(ComboGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TxtGenero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(DataFecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(TxtIdioma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(TxtSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(BtnAgregar)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAgregarActionPerformed
        // TODO add your handling code here:
        AgrgarPelicula();
    }//GEN-LAST:event_BtnAgregarActionPerformed

    private void TxtDirectorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtDirectorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtDirectorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAgregar;
    private javax.swing.JComboBox<String> ComboGenero;
    private com.toedter.calendar.JDateChooser DataFecha;
    private javax.swing.JTextField TxtDirector;
    private javax.swing.JTextField TxtDuracion;
    private javax.swing.JTextField TxtGenero;
    private javax.swing.JTextField TxtIdioma;
    private javax.swing.JTextField TxtSinopsis;
    private javax.swing.JTextField TxtTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
