/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.Cuenta;
import cine.Clases.ConexionBD;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import java.util.ArrayList;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author 57300
 */
public class JIFrmTicket extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmTicket
     */
    
    ConexionBD conn;
    int id;
    
    String titulo,Sala,Inicio,Fin,sillas;
    double total;
    ArrayList<Integer> silla;
    ArrayList<Integer> asientoId = new  ArrayList();
    ArrayList<Integer> idreserva = new  ArrayList();
    private Cuenta cuenta;
 
    public JIFrmTicket(int id,String titulo,String Sala,String Inicio,String Fin,double total,Cuenta cuenta, ArrayList asientoId) {
        initComponents();
        this.id = id;
        this.titulo = titulo;
        this.Sala = Sala;
        this.Inicio = Inicio;
        this.Fin = Fin;
        this.total = total;
        this.cuenta = cuenta;
        this.asientoId = asientoId;
        silla = new ArrayList();
        conn = new ConexionBD();
        cambiardatos();
        addInternalFrameListener(new javax.swing.event.InternalFrameAdapter() {
            @Override
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent e) {
                int respuesta = JOptionPane.showConfirmDialog(null, "¿Cancelar la reserva?");
                if (respuesta == JOptionPane.YES_OPTION) {
                    cancelarAsiento();
                    dispose();
                }
            }
        });
        setDefaultCloseOperation(JInternalFrame.DO_NOTHING_ON_CLOSE);
    }
    
    public void cambiardatos(){
        Lblpelicula.setText(titulo);
        LblInicio.setText(Inicio);
        LblFin.setText(Fin);
        LblSala.setText(Sala);
        LblPrecio.setText(""+total);   
        StringBuilder texto = new StringBuilder("");

        for (int i = 0; i < silla.size(); i++) {
            texto.append(silla.get(i));
            if (i < silla.size() - 1) {
                texto.append(", ");
            }
        }
        LblSillas.setText(texto.toString());
        sillas = texto.toString();
    }
    
    public void insertarReserva(int idc , double total){
        int ide = cuenta.getIde();
        try {
            Connection con = conn.Conexion();
            CallableStatement cstmt = con.prepareCall("call insertar_reserva(?, ?, ?, ?)");
            
            if (idc == 0) {
                cstmt.setNull(1, Types.INTEGER);
                cstmt.setInt(2,ide); 
            } else {
                cstmt.setInt(1, idc);
                cstmt.setNull(2, Types.INTEGER); 
            }                  
                               
            cstmt.setDouble(3, total);
            cstmt.registerOutParameter(4, Types.INTEGER);            
            
            cstmt.execute();
            int reservaId = cstmt.getInt(4);  
            
            idreserva.clear();
            idreserva.add(reservaId);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: al guardar " + e.getMessage());
        }
    }
    
    private void cancelarAsiento() {
        for (int i = 0; i < asientoId.size(); i++) {
            int idAsiento = asientoId.get(i);
            try{
                Connection con = conn.Conexion();
                String sql = "call eliminar_asiento(?)";
                CallableStatement cstmt = con.prepareCall(sql);
               cstmt.setInt(1, idAsiento);
               int filas = cstmt.executeUpdate();

               if (filas > 0) {
                   JOptionPane.showMessageDialog(null, "Asiento cancelado");
               } else {
                   JOptionPane.showMessageDialog(null, "No se encontró el asiento");
               }

           } catch (Exception e) {
               JOptionPane.showMessageDialog(null, "Error al cancelar asiento: " + e.getMessage());
           }
        }  
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        LblInicio = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblSillas = new javax.swing.JLabel();
        BtnComprar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        LblFin = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LblSala = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Lblpelicula = new javax.swing.JLabel();
        LblPrecio = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(139, 220, 224));

        LblInicio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblInicio.setText("jLabel2");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Sillas:");

        LblSillas.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblSillas.setText("jLabel4");

        BtnComprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnComprar.setText("Comprar");
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Fin:");

        LblFin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblFin.setText("jLabel2");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Sala:");

        LblSala.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblSala.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Pelicula:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Precio:");

        Lblpelicula.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Lblpelicula.setText("jLabel2");

        LblPrecio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblPrecio.setText("jLabel2");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Iniocio:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblSillas))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(33, 33, 33)
                                .addComponent(LblInicio)))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel7))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LblFin)
                                    .addComponent(LblSala)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(LblPrecio))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(Lblpelicula)))
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BtnComprar)
                .addGap(137, 137, 137))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Lblpelicula)
                    .addComponent(jLabel8)
                    .addComponent(LblSala))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(LblInicio)
                    .addComponent(jLabel7)
                    .addComponent(LblFin))
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(LblSillas)
                    .addComponent(jLabel9)
                    .addComponent(LblPrecio))
                .addGap(49, 49, 49)
                .addComponent(BtnComprar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        // TODO add your handling code here:
           insertarReserva(cuenta.getId(),  total);
           
           int reserva = idreserva.get(0);
           
           JIFrmPago pago = new JIFrmPago(reserva, id, total, cuenta,asientoId);
           getDesktopPane().add(pago);
           pago.setVisible(true);
           this.setVisible(false);
    }//GEN-LAST:event_BtnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnComprar;
    private javax.swing.JLabel LblFin;
    private javax.swing.JLabel LblInicio;
    private javax.swing.JLabel LblPrecio;
    private javax.swing.JLabel LblSala;
    private javax.swing.JLabel LblSillas;
    private javax.swing.JLabel Lblpelicula;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
