/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.Peliculas;
import cine.Clases.ConexionBD;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author 57300
 */
public class JIFrmBuscarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmBuscarPelicula
     */
     Peliculas pelicula;
    ConexionBD conn;
     
    public JIFrmBuscarPelicula() {
        initComponents();
        conn = new ConexionBD();
        LlenarComboPeliculas(ComboBuscar, pelicula);
        canbiarTamaño();
    }
    
    
    public void SelecionPelicula(){
        pelicula = (Peliculas) ComboBuscar.getSelectedItem();
        if(ComboBuscar.getSelectedIndex() > 0){
            LblTitulo.setText(pelicula.getTitulo());
            LblDirecto.setText(pelicula.getDirector());
            LblDuracion.setText(pelicula.getDuracion());
            LblSinopsis.setText(pelicula.getSinopsis());
            LblGenero.setText(pelicula.getGenero());
        }else{
            pelicula = null;
        }
        
    }
    
    public void canbiarTamaño(){
        if(ComboBuscar.getSelectedIndex() == 0){
            this.setSize(560, 120);
            LblDirecto.setVisible(false);
            LblDuracion.setVisible(false);
            LblGenero.setVisible(false);
            LblImagen.setVisible(false);
            LblSinopsis.setVisible(false);
            LblTitulo.setVisible(false);
            BtnComprar.setVisible(false);
        }else{
            this.setSize(500, 560);
            LblDirecto.setVisible(true);
            LblDuracion.setVisible(true);
            LblGenero.setVisible(true);
            LblImagen.setVisible(true);
            LblSinopsis.setVisible(true);
            LblTitulo.setVisible(true);
            BtnComprar.setVisible(true);
        }
    }
    
    public void LlenarComboPeliculas(JComboBox Combo,Peliculas pelicula){
        try {
            Connection con = conn.Conexion();
            String sql = "call peliculas_completo()";
            
            CallableStatement  cstmt  = con.prepareCall(sql);
            
            ResultSet resultado = cstmt .executeQuery();
            
            Combo.removeAllItems();
            Peliculas placeholder = new Peliculas(0, "Seleccione una película", "", "", "", "", "", "");
            Combo.addItem(placeholder);
            
            while(resultado.next()){
                int id = resultado.getInt("pelicula_id");
                String titulo = resultado.getString("titulo");
                String genero = resultado.getString("nombre_genero");
                String duracion = resultado.getString("duracion_minutes");
                String estreno = resultado.getString("fecha_estreno");
                String director = resultado.getString("director");
                String sinopsis = resultado.getString("sinopsis");
                String idioma = resultado.getString("idioma");
                pelicula = new Peliculas(id, titulo, genero, duracion, estreno, director, sinopsis, idioma);
                Combo.addItem(pelicula);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la pelicula" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnComprar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        ComboBuscar = new javax.swing.JComboBox<>();
        LblImagen = new javax.swing.JLabel();
        LblDirecto = new javax.swing.JLabel();
        LblDuracion = new javax.swing.JLabel();
        LblGenero = new javax.swing.JLabel();
        LblSinopsis = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(139, 220, 224));

        BtnComprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnComprar.setText("Reservar");
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });

        BtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });

        ComboBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        LblImagen.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblImagen.setText("jLabel1");

        LblDirecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblDirecto.setText("jLabel2");

        LblDuracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblDuracion.setText("jLabel3");

        LblGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblGenero.setText("jLabel4");

        LblSinopsis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblSinopsis.setText("jLabel5");

        LblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTitulo.setText("jLabel6");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(LblDirecto)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(LblSinopsis, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(BtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(61, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(LblGenero)
                            .addComponent(LblTitulo)
                            .addComponent(LblImagen))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LblDuracion)
                        .addGap(79, 79, 79))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(194, 194, 194)
                .addComponent(BtnComprar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnBuscar)
                    .addComponent(ComboBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(LblImagen)
                .addGap(91, 91, 91)
                .addComponent(LblTitulo)
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblDirecto)
                    .addComponent(LblGenero)
                    .addComponent(LblDuracion))
                .addGap(37, 37, 37)
                .addComponent(LblSinopsis, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(BtnComprar)
                .addGap(46, 46, 46))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        SelecionPelicula();
        canbiarTamaño();
    }//GEN-LAST:event_BtnBuscarActionPerformed

    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        // TODO add your handling code here:
        if (pelicula != null) {
            JIFrmComprar comprar = new JIFrmComprar(0);
            comprar.mostrarInfo(pelicula);
            getDesktopPane().add(comprar);
            comprar.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una película antes de comprar.");
        }
        
    }//GEN-LAST:event_BtnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JComboBox<String> ComboBuscar;
    private javax.swing.JLabel LblDirecto;
    private javax.swing.JLabel LblDuracion;
    private javax.swing.JLabel LblGenero;
    private javax.swing.JLabel LblImagen;
    private javax.swing.JLabel LblSinopsis;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
