/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.ConexionBD;
import cine.Clases.Cuenta;
import cine.FrmPrincipal.FrmLogin;
import cine.FrmPrincipal.JIFrmMenu;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author 57300
 */
public class JIFrmPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmPerfil
     */
    
    ConexionBD conn;
    Cuenta cuentas;
    int idPersona;
    String tipo;
    public JIFrmPerfil( Cuenta cuenta) {
        initComponents();
        conn = new ConexionBD();
        this.cuentas = cuenta;
        tipo = cuentas.getRol();
        
        // aqui se hace una validacion para saber la id del cliente o el empleado
        idPersona = cuentas.getId();
        if(idPersona == 0){
            idPersona= cuenta.getIde();
        }
        mostrarPerfilPorId();
    }
    
    
    // aqui se solicitan los datos que se necesitan para mostrar 
    // en la ventana y se hace una validacion para mostrar un 
    // lbl que se muestra dependiendo del rol que tiene la persona
    public void mostrarPerfilPorId() {
        
        try{
            Connection con = conn.Conexion();
            String sql = "call perfil(?, ?)";
            CallableStatement cstmt = con.prepareCall(sql);
            cstmt.setString(1, tipo); 
            cstmt.setInt(2, idPersona);

            ResultSet rs = cstmt.executeQuery();

            if (rs.next()) {
                String nombre   = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                String email    = rs.getString("email");
                String telefono = rs.getString("telefono");
                String usuario  = rs.getString("usuario");
                String rol      = rs.getString("rol");
                
                if(rol.equalsIgnoreCase("cliente")){
                    LblCargo1.setVisible(false);
                    lblCargo2.setVisible(false);
                    LblNombre.setText(nombre);
                    LblApellido.setText(apellido);
                    LblEmail.setText(email);
                    LblUsuario.setText(usuario);
                }else{
                    LblCargo1.setVisible(true);
                    lblCargo2.setVisible(true);
                    lblCargo2.setText(rol);
                    LblNombre.setText(nombre);
                    LblApellido.setText(apellido);
                    LblEmail.setText(email);
                    LblUsuario.setText(usuario);
                }               
                
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el " + tipo + " con ID " + idPersona);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        LblApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblCargo1 = new javax.swing.JLabel();
        lblCargo2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jPanel1.setBackground(new java.awt.Color(139, 220, 224));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Apellido");

        LblApellido.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblApellido.setText("jLabel4");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Email");

        LblEmail.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblEmail.setText("jLabel6");

        LblCargo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblCargo1.setText("Cargo");

        lblCargo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCargo2.setText("jLabel8");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Usuario");

        LblUsuario.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblUsuario.setText("jLabel10");

        BtnCerrarSesion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnCerrarSesion.setText("Cerrar sesion");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre");

        LblNombre.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblNombre.setText("jLabel2");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnCerrarSesion)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(LblNombre))
                                .addGap(47, 47, 47)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(LblApellido)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LblEmail))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(52, 52, 52)
                                        .addComponent(jLabel5)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCargo1)
                            .addComponent(lblCargo2)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblUsuario)
                            .addComponent(jLabel9))
                        .addGap(276, 276, 276)))
                .addGap(41, 41, 41))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(LblCargo1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LblNombre)
                    .addComponent(LblApellido)
                    .addComponent(LblEmail)
                    .addComponent(lblCargo2))
                .addGap(26, 26, 26)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(LblUsuario)
                .addGap(18, 18, 18)
                .addComponent(BtnCerrarSesion)
                .addContainerGap(53, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    // aqui se cierra la sesion y cierra la ventana perfil y el principal para redireccionar al login 
    // con SwingUtilities se pregunta por la ventana padre y dispose para cerrar las dos ventanas
    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        // TODO add your handling code here:
        
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblCargo1;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCargo2;
    // End of variables declaration//GEN-END:variables
}
