/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.Peliculas;
import cine.Clases.ConexionBD;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JComboBox;
import javax.swing.JOptionPane;

/**
 *
 * @author 57300
 */
public class JIFrmBuscarPelicula extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmBuscarPelicula
     */
     Peliculas pelicula;
    ConexionBD conn;
     
    public JIFrmBuscarPelicula() {
        initComponents();
        conn = new ConexionBD();
        LlenarComboPeliculas(ComboBuscar, pelicula);
        canbiarTamaño();
    }
    
    // aqui se cabian los datos por la informacin del ticket segun la pelicula seleccionada
    public void SelecionPelicula(){
        pelicula = (Peliculas) ComboBuscar.getSelectedItem();
        if(ComboBuscar.getSelectedIndex() > 0){
            LblTitulo.setText(pelicula.getTitulo());
            LblDirecto.setText(pelicula.getDirector());
            LblDuracion.setText(pelicula.getDuracion());
            LblSinopsis.setText(pelicula.getSinopsis());
            LblGenero.setText(pelicula.getGenero());
        }else{
            pelicula = null;
        }
        
    }
    
    // esto es para cuando no hay nada seleccionado no se vea todo grande el 
    // panel y ya cuando se seleccione tome el tamaño necesario para mostrar la informacion de la pelicula
    public void canbiarTamaño(){
        if(ComboBuscar.getSelectedIndex() == 0){
            this.setSize(560, 120);
            LblDirecto.setVisible(false);
            LblDuracion.setVisible(false);
            LblGenero.setVisible(false);
            LblSinopsis.setVisible(false);
            LblTitulo.setVisible(false);
            BtnComprar.setVisible(false);
        }else{
            this.setSize(500, 560);
            LblDirecto.setVisible(true);
            LblDuracion.setVisible(true);
            LblGenero.setVisible(true);
            LblSinopsis.setVisible(true);
            LblTitulo.setVisible(true);
            BtnComprar.setVisible(true);
        }
    }
    
    // aqui consultamos y rrellenamos el combo con la infomacion dada de la base de datos de las peliculas
    public void LlenarComboPeliculas(JComboBox Combo,Peliculas pelicula){
        try {
            Connection con = conn.Conexion();
            String sql = "call peliculas_completo()";
            
            CallableStatement  cstmt  = con.prepareCall(sql);
            
            ResultSet resultado = cstmt .executeQuery();
            
            Combo.removeAllItems();
            Peliculas placeholder = new Peliculas(0, "Seleccione una película", "", "", "", "", "", "");
            Combo.addItem(placeholder);
            
            while(resultado.next()){
                int id = resultado.getInt("pelicula_id");
                String titulo = resultado.getString("titulo");
                String genero = resultado.getString("nombre_genero");
                String duracion = resultado.getString("duracion_minutes");
                String estreno = resultado.getString("fecha_estreno");
                String director = resultado.getString("director");
                String sinopsis = resultado.getString("sinopsis");
                String idioma = resultado.getString("idioma");
                pelicula = new Peliculas(id, titulo, genero, duracion, estreno, director, sinopsis, idioma);
                Combo.addItem(pelicula);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error al cargar la pelicula" + e);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BtnComprar = new javax.swing.JButton();
        BtnBuscar = new javax.swing.JButton();
        ComboBuscar = new javax.swing.JComboBox<>();
        LblDirecto = new javax.swing.JLabel();
        LblDuracion = new javax.swing.JLabel();
        LblGenero = new javax.swing.JLabel();
        LblSinopsis = new javax.swing.JLabel();
        LblTitulo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setBackground(new java.awt.Color(139, 220, 224));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BtnComprar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnComprar.setText("Reservar");
        BtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnComprarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 460, -1, -1));

        BtnBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        BtnBuscar.setText("Buscar");
        BtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBuscarActionPerformed(evt);
            }
        });
        jPanel1.add(BtnBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(327, 26, 100, -1));

        ComboBuscar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ComboBuscar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(ComboBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(34, 26, 251, -1));

        LblDirecto.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblDirecto.setText("jLabel2");
        jPanel1.add(LblDirecto, new org.netbeans.lib.awtextra.AbsoluteConstraints(42, 215, -1, -1));

        LblDuracion.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblDuracion.setText("jLabel3");
        jPanel1.add(LblDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 220, -1, -1));

        LblGenero.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblGenero.setText("jLabel4");
        jPanel1.add(LblGenero, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 220, -1, -1));

        LblSinopsis.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblSinopsis.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        LblSinopsis.setToolTipText("");
        LblSinopsis.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        LblSinopsis.setMaximumSize(new java.awt.Dimension(300, 15));
        LblSinopsis.setPreferredSize(new java.awt.Dimension(400, 80));
        jPanel1.add(LblSinopsis, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 400, 140));

        LblTitulo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LblTitulo.setText("jLabel6");
        jPanel1.add(LblTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("TITULO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("DIRECTOR");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("GENERO");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("DURACION");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 170, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("SIPNOSIS");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        getContentPane().add(jPanel1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBuscarActionPerformed
        // TODO add your handling code here:
        SelecionPelicula();
        canbiarTamaño();
    }//GEN-LAST:event_BtnBuscarActionPerformed
    
    // aqui una validacion para que seleccione una pelicula 
    private void BtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnComprarActionPerformed
        // TODO add your handling code here:
        if (pelicula != null) {
            JIFrmComprar comprar = new JIFrmComprar(0);
            comprar.mostrarInfo(pelicula);
            getDesktopPane().add(comprar);
            comprar.setVisible(true);
            this.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(rootPane, "Debe seleccionar una película antes de comprar.");
        }
        
    }//GEN-LAST:event_BtnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBuscar;
    private javax.swing.JButton BtnComprar;
    private javax.swing.JComboBox<String> ComboBuscar;
    private javax.swing.JLabel LblDirecto;
    private javax.swing.JLabel LblDuracion;
    private javax.swing.JLabel LblGenero;
    private javax.swing.JLabel LblSinopsis;
    private javax.swing.JLabel LblTitulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
