/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package cine.FrmInternas;

import cine.Clases.ConexionBD;
import cine.Clases.Cuenta;
import cine.FrmPrincipal.FrmLogin;
import cine.FrmPrincipal.JIFrmMenu;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
/**
 *
 * @author 57300
 */
public class JIFrmPerfil extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFrmPerfil
     */
    
    ConexionBD conn;
    Cuenta cuentas;
    int idPersona;
    String tipo;
    public JIFrmPerfil( Cuenta cuenta) {
        initComponents();
        conn = new ConexionBD();
        this.cuentas = cuenta;
        tipo = cuentas.getRol();
        idPersona = cuentas.getId();
        if(idPersona == 0){
            idPersona= cuenta.getIde();
        }
        mostrarPerfilPorId();
    }
    
    public void mostrarPerfilPorId() {
        
        try{
            Connection con = conn.Conexion();
            String sql = "call perfil(?, ?)";
            CallableStatement cstmt = con.prepareCall(sql);
            cstmt.setString(1, tipo); 
            cstmt.setInt(2, idPersona);

            ResultSet rs = cstmt.executeQuery();

            if (rs.next()) {
                String nombre   = rs.getString("nombre");
                String apellido = rs.getString("apellido");
                String email    = rs.getString("email");
                String telefono = rs.getString("telefono");
                String usuario  = rs.getString("usuario");
                String rol      = rs.getString("rol");
                
                if(rol.equalsIgnoreCase("cliente")){
                    LblCargo1.setVisible(false);
                    lblCargo2.setVisible(false);
                    LblNombre.setText(nombre);
                    LblApellido.setText(apellido);
                    LblEmail.setText(email);
                    LblUsuario.setText(usuario);
                }else{
                    LblCargo1.setVisible(true);
                    lblCargo2.setVisible(true);
                    lblCargo2.setText(rol);
                    LblNombre.setText(nombre);
                    LblApellido.setText(apellido);
                    LblEmail.setText(email);
                    LblUsuario.setText(usuario);
                }               
                
            } else {
                JOptionPane.showMessageDialog(null, "No se encontró el " + tipo + " con ID " + idPersona);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        LblNombre = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        LblApellido = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LblEmail = new javax.swing.JLabel();
        LblCargo1 = new javax.swing.JLabel();
        lblCargo2 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        LblUsuario = new javax.swing.JLabel();
        BtnCerrarSesion = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        jLabel1.setText("Nomrbe");

        LblNombre.setText("jLabel2");

        jLabel3.setText("Apellido");

        LblApellido.setText("jLabel4");

        jLabel5.setText("Email");

        LblEmail.setText("jLabel6");

        LblCargo1.setText("Cargo");

        lblCargo2.setText("jLabel8");

        jLabel9.setText("Usuario");

        LblUsuario.setText("jLabel10");

        BtnCerrarSesion.setText("Cerrar sesion");
        BtnCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCerrarSesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LblUsuario)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(LblNombre))
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LblApellido)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LblEmail))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(52, 52, 52)
                                .addComponent(jLabel5)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LblCargo1)
                            .addComponent(lblCargo2))
                        .addGap(40, 40, 40))))
            .addGroup(layout.createSequentialGroup()
                .addGap(149, 149, 149)
                .addComponent(BtnCerrarSesion)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5)
                    .addComponent(LblCargo1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LblNombre)
                            .addComponent(LblApellido)
                            .addComponent(LblEmail)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(lblCargo2)))
                .addGap(16, 16, 16)
                .addComponent(jLabel9)
                .addGap(18, 18, 18)
                .addComponent(LblUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(BtnCerrarSesion)
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCerrarSesionActionPerformed
        // TODO add your handling code here:
        
        FrmLogin login = new FrmLogin();
        login.setVisible(true);
        SwingUtilities.getWindowAncestor(this).dispose();
    }//GEN-LAST:event_BtnCerrarSesionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCerrarSesion;
    private javax.swing.JLabel LblApellido;
    private javax.swing.JLabel LblCargo1;
    private javax.swing.JLabel LblEmail;
    private javax.swing.JLabel LblNombre;
    private javax.swing.JLabel LblUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblCargo2;
    // End of variables declaration//GEN-END:variables
}
